#!/bin/sh

# Please note it's not a system-wide settings, it's only for a current
# terminal session. Point your f\w (if necessery) to execute /kip/etc/profile
# at console logon.

is_substring(){
    case "$2" in
        *$1*) return 0;;
        *) return 1;;
    esac
}

# Set CHECK_OPT_PATH to 1 to check /kip/bin and /kip/sbin in PATH
CHECK_OPT_PATH=0
if [ $CHECK_OPT_PATH = 1 ]; then
    is_substring "/kip/bin" $PATH
    [ $? == 1 ] && export PATH=/kip/bin:$PATH
    is_substring "/kip/sbin" $PATH
    [ $? == 1 ] && export PATH=/kip/sbin:$PATH
else
    export PATH=/kip/bin:/kip/sbin:$PATH
fi
export TERMINFO=/kip/share/terminfo
export TERM=xterm
export TMP=/kip/tmp
export TEMP=/kip/tmp
unset LD_PRELOAD
unset LD_LIBRARY_PATH
alias mc="mc -c"

# You may define localization
#export LANG='ru_RU.UTF-8'
#export LC_ALL='ru_RU.UTF-8'
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
